# Generated by Django 3.2.10 on 2021-12-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.URLField(),
        ),
    ]
