# Generated by Django 3.2.10 on 2021-12-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
