# Generated by Django 4.0 on 2022-01-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBarButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('page', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DropDownButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('navbar_button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.navbarbutton')),
            ],
        ),
    ]
