# Generated by Django 4.0 on 2022-01-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_navbarbutton_dropdownbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarbutton',
            name='has_dropdown',
            field=models.BooleanField(default=False),
        ),
    ]
