# Generated by Django 4.0 on 2022-01-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_navbarbutton_has_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownbutton',
            name='data',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navbarbutton',
            name='page',
            field=models.CharField(max_length=100),
        ),
    ]
