# Generated by Django 4.0 on 2022-02-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_alter_dropdownbutton_data_alter_navbarbutton_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownbutton',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='navbarbutton',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
