# Generated by Django 3.2.10 on 2021-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211214_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='folio/apps/projects/static/projects/images'),
        ),
    ]
